apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: rdembio/hello-gitops
  newTag: f8c3df9b7c194234d604ab5910666f80367e2982
